[package]
name = "packster-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features=["derive"] }
hex = { version = "0.4.3", features=["serde"] }
lazy_static = "1.4.0"
regex = "1.8.1"

[dev-dependencies]
pretty_assertions = "1.3.0"