[package]
name = "packster"
version = "0.1.0"
edition = "2021"

[dependencies]
indoc = "2.0.0"
normpath = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.0"
uniqueid = "0.2.6"
sha2= "0.10.6"
tar = "0.4.38"
flate2 = "1.0.25"
hex = "0.4.3"
walkdir = "2.3.2"
