[package]
name = "packster-infrastructure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packster-core = { path = "../packster-core" }
sha2 = "0.10.6"
tar = "0.4.38"
flate2 = "1.0.25"
walkdir = "2.3.2"
uniqueid = "0.2.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.0"

[features]
test = []